name: Run Scrapers

on:
  workflow_dispatch:   # allow manual run from Actions tab
  schedule:
    - cron: "0 0 * * 0"   # run weekly (Sunday midnight UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pdfplumber

      - name: Run scrapers
        run: |
          cd scraper
          python crosswalk_parser.py
          python clean_crosswalk.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ../data/*.json
          git commit -m "Update scraped crosswalk data" || echo "No changes"
          git push
